# Generated by Django 6.0.3 on 2026-06-01 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_student_id_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['employee_id']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.AlterField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_form',
            field=models.CharField(blank=True, help_text='Form/class at time of admission (e.g., Form 1)', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of admission (e.g., 2026)', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, help_text='Current class assignment (can change with promotions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Legacy registration number. Kept for backward compatibility.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(db_index=True, editable=False, help_text='Auto-generated Student ID (e.g., NZS-26-F1-0001). Cannot be changed.', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
