# Generated by Django 6.0.3 on 2026-06-02 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_class_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_elective', models.BooleanField(default=False, help_text='True if added as an elective (not a compulsory subject).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Subject',
                'verbose_name_plural': 'Student Subjects',
                'ordering': ['subject__name'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('CORE', 'Core / Compulsory'), ('SCIENCE', 'Science'), ('HUMANITIES', 'Humanities'), ('COMMERCIAL', 'Commercial'), ('TECHNICAL', 'Technical'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_compulsory',
            field=models.BooleanField(db_index=True, default=False, help_text='Compulsory subjects are automatically assigned to every student.'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_compulsory', 'category'], name='accounts_su_is_comp_6e71be_idx'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects', to='accounts.subject'),
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['student', 'subject'], name='accounts_st_student_0def50_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['subject', 'student'], name='accounts_st_subject_76e2f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together={('student', 'subject')},
        ),
    ]
