# Generated by Django 4.2.7 on 2026-06-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_compulsory_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st', 'First Term'), ('2nd', 'Second Term'), ('3rd', 'Third Term')], db_index=True, max_length=3)),
                ('session', models.CharField(db_index=True, help_text='Academic session, e.g. 2025-2026', max_length=9)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Only one term should be active at a time.')),
                ('registration_open', models.BooleanField(default=False, help_text='Students can register subjects when this is enabled.')),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Optional deadline — registration auto-closes after this date.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'ordering': ['-session', 'term'],
                'unique_together': {('term', 'session')},
            },
        ),
        migrations.CreateModel(
            name='SubjectRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_registrations', to='accounts.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_registrations', to='accounts.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.academicterm')),
            ],
            options={
                'verbose_name': 'Subject Registration',
                'verbose_name_plural': 'Subject Registrations',
                'ordering': ['term', 'subject__name'],
                'indexes': [models.Index(fields=['student', 'term'], name='accounts_su_student_f1519d_idx'), models.Index(fields=['term', 'subject'], name='accounts_su_term_id_47dab2_idx')],
                'unique_together': {('student', 'subject', 'term')},
            },
        ),
    ]
