# Generated by Django 5.1.6 on 2026-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_academicterm_subjectregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='must_change_password',
            field=models.BooleanField(default=False, editable=False, help_text='Student must change password on next login.'),
        ),
    ]
