services:
  - type: web
    name: school-portal
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt && \
      cd school_portal && \
      python manage.py collectstatic --noinput && \
      python manage.py migrate

    startCommand: cd school_portal && gunicorn school_portal.wsgi:application

    envVars:
      - key: DEBUG
        value: "False"

      - key: SECRET_KEY
        generateValue: true

      - key: ALLOWED_HOSTS
        value: ".onrender.com"

      - key: DATABASE_URL
        fromDatabase:
          name: school-portal-db
          property: connectionString

databases:
  - name: school-portal-db
    databaseName: school_portal_db
    plan: free