# Generated by Django 4.2.7 on 2026-05-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0004_alter_result_subject'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_id',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
