# Generated by Django 6.0.3 on 2026-06-01 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0002_feestructure_studentinvoice_bankpaymentreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Nazarene Secondary School', max_length=200)),
                ('school_motto', models.CharField(blank=True, default='Excellence & Integrity', max_length=200)),
                ('school_phone', models.CharField(blank=True, max_length=30)),
                ('school_email', models.EmailField(blank=True, max_length=254)),
                ('school_address', models.CharField(blank=True, max_length=255)),
                ('receipt_prefix', models.CharField(default='RCP', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee Configuration',
                'verbose_name_plural': 'Fee Configuration',
            },
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountant_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accountant',
                'verbose_name_plural': 'Accountants',
                'ordering': ['accountant_id'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('student_id', models.CharField(db_index=True, max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Outstanding balance after this payment was applied.', max_digits=12)),
                ('term', models.CharField(max_length=3)),
                ('academic_year', models.CharField(max_length=9)),
                ('date_issued', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_receipts', to='parents.studentinvoice')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_issued', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(help_text='The bank payment this receipt is issued for.', on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='parents.bankpaymentreceipt')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve_payment', 'Approved Payment'), ('reject_payment', 'Rejected Payment'), ('record_payment', 'Recorded Payment'), ('create_fee_structure', 'Created Fee Structure'), ('update_fee_structure', 'Updated Fee Structure'), ('create_invoice', 'Created Invoice'), ('submit_bank_slip', 'Bank Slip Submitted'), ('issue_receipt', 'Receipt Issued'), ('download_receipt', 'Receipt Downloaded'), ('view_report', 'Viewed Report')], db_index=True, max_length=40)),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('target_model', models.CharField(blank=True, max_length=60)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=60)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='fees_auditl_action_c2a28b_idx'), models.Index(fields=['target_model', 'target_id'], name='fees_auditl_target__8d709f_idx')],
            },
        ),
    ]
