# Generated by Django 4.2.7 on 2026-06-02 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_alter_bankpaymentreceipt_invoice'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_receipts', to='parents.studentinvoice'),
        ),
    ]
