# Generated by Django 5.1.6 on 2026-06-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_receipt_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='term',
            field=models.CharField(choices=[('1st', 'First Term'), ('2nd', 'Second Term'), ('3rd', 'Third Term')], db_index=True, max_length=3),
        ),
    ]
