# Generated by Django 6.0.3 on 2026-06-01 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_class_options_alter_student_options_and_more'),
        ('parents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Term 1 Tuition Fee', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in MWK', max_digits=12)),
                ('term', models.CharField(choices=[('1st', 'First Term'), ('2nd', 'Second Term'), ('3rd', 'Third Term')], max_length=3)),
                ('session', models.CharField(help_text='e.g., 2026-2027', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_class', models.ForeignKey(blank=True, help_text='Leave blank if this fee applies to all classes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='accounts.class')),
            ],
            options={
                'ordering': ['-session', 'term', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='parents.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'fee_structure')},
            },
        ),
        migrations.CreateModel(
            name='BankPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('nbm', 'National Bank of Malawi'), ('standard', 'Standard Bank'), ('nbs', 'NBS Bank'), ('fdh', 'FDH Bank'), ('fcb', 'First Capital Bank'), ('ecobank', 'EcoBank'), ('mybucks', 'MyBucks'), ('other', 'Other')], max_length=20)),
                ('depositor_name', models.CharField(help_text='Name of the person who made the deposit', max_length=150)),
                ('transaction_reference', models.CharField(help_text='Unique reference number stamped on the bank slip', max_length=100, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount deposited in MWK', max_digits=12)),
                ('payment_date', models.DateField(help_text='Date of deposit at the bank')),
                ('deposit_slip_image', models.ImageField(help_text='Clear photo or scan of the stamped deposit slip', upload_to='deposit_slips/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved / Paid'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection, visible to parents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_receipts', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='parents.studentinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
