# Generated by Django 5.1.6 on 2026-06-20 16:29

import django.db.models.deletion
import django.db.models.deletion
from django.db import migrations, models


def backfill_student(apps, schema_editor):
    BankPaymentReceipt = apps.get_model('parents', 'BankPaymentReceipt')
    for receipt in BankPaymentReceipt.objects.select_related('invoice__student').iterator():
        if receipt.invoice_id and not receipt.student_id:
            receipt.student = receipt.invoice.student
            receipt.save(update_fields=['student'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_must_change_password'),
        ('parents', '0004_alter_bankpaymentreceipt_invoice_nonnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpaymentreceipt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='bankpaymentreceipt',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='parents.studentinvoice'),
        ),
        migrations.RunPython(backfill_student, migrations.RunPython.noop),
    ]
